-- ============================================================
-- QARARI.AI — DEVICE FINGERPRINT USAGE TRACKING MIGRATION
-- Run this in Supabase SQL Editor (Project → SQL Editor → New Query)
-- ============================================================
-- Purpose: Move free-scan tracking from IP-only (client-bypassable)
-- to server-side device fingerprint + IP aliasing so guests cannot
-- reset their quota by clearing cookies, switching browsers, or
-- reinstalling the PWA.
-- ============================================================

-- 1. NEW TABLE: device_usage_logs
-- One row per (device_fingerprint, month) that tracks the cumulative
-- scan count for that device. The device_fingerprint is a stable hash
-- generated by FingerprintJS on the client and sent to the server.
create table if not exists public.device_usage_logs (
  id uuid primary key default gen_random_uuid(),
  device_fingerprint text not null,
  ip_address text,
  user_agent text,
  scans_used_this_month int not null default 0,
  scans_reset_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  UNIQUE (device_fingerprint, scans_reset_at)
);

create index if not exists device_usage_logs_fingerprint_idx
  on public.device_usage_logs (device_fingerprint);
create index if not exists device_usage_logs_ip_idx
  on public.device_usage_logs (ip_address);
create index if not exists device_usage_logs_reset_idx
  on public.device_usage_logs (scans_reset_at);

-- 2. NEW TABLE: guest_device_aliases
-- When a new fingerprint appears from an IP that already has 2+ devices
-- within 24 hours, we alias the new fingerprint to the existing one.
-- This prevents simple fingerprint evasion on the same network/device.
create table if not exists public.guest_device_aliases (
  id uuid primary key default gen_random_uuid(),
  device_fingerprint text not null,
  primary_fingerprint text not null,
  ip_address text not null,
  created_at timestamptz not null default now(),
  UNIQUE (device_fingerprint)
);

create index if not exists guest_device_aliases_primary_idx
  on public.guest_device_aliases (primary_fingerprint);
create index if not exists guest_device_aliases_fingerprint_idx
  on public.guest_device_aliases (device_fingerprint);

-- 3. Add linked_fingerprint column to guest_usage for backward compatibility
-- and migration linking (links IP to primary fingerprint)
alter table public.guest_usage add column if not exists linked_fingerprint text;
create index if not exists guest_usage_linked_fingerprint_idx
  on public.guest_usage (linked_fingerprint);

-- No RLS policies needed — all access is via Supabase service role key
-- from the backend only. The browser never queries these tables directly.
